# Generated by Django 4.0 on 2023-12-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Name',
            new_name='UserName',
        ),
    ]
